import { createOpenAPI } from "fumadocs-openapi/server";
import { createAPIPage } from "fumadocs-openapi/ui";
import path from "node:path";

/**
 * OpenAPI server bound to the repo's committed contract snapshot.
 *
 * @remarks
 * Single source of truth for the docs zone's `<APIPage>` component.
 * `openapi.snapshot.json` lives at the repo root and is regenerated by
 * the contract test (`tests/contract/openapi.test.ts`) on every CI
 * run — so the rendered API reference can never drift from the live
 * Zod validators.
 *
 * `input` uses the **function form** (`() => SchemaMap`) so MDX files
 * can reference the document by a stable key (`"openapi.snapshot.json"`)
 * rather than the absolute file path that the `string[]` form would
 * require — `path.resolve` happens once on the server, the rendered
 * MDX stays portable.
 *
 * @see tests/contract/openapi.test.ts — the spec generator.
 * @see openapi.snapshot.json — the committed source.
 */
export const openapi = createOpenAPI({
  input: () => ({
    "openapi.snapshot.json": path.resolve("./openapi.snapshot.json"),
  }),
});

/**
 * The `<APIPage>` component used in MDX files under `_content/api/`.
 *
 * @remarks
 * Wired into MDX components in `[...slug]/page.tsx` so MDX can
 * reference operations as
 * `<APIPage document="openapi.snapshot.json" operations={[...]} />`
 * — the path/method tuple looks the operation up in the OpenAPI doc
 * and renders the full request/response detail.
 *
 * `shikiOptions` matches Fumadocs's canonical pairing — `github-light`
 * for the light theme + `vesper` for dark — so OpenAPI code samples
 * share the visual identity of the prose code blocks alongside them.
 */
export const APIPage = createAPIPage(openapi, {
  shikiOptions: {
    themes: {
      light: "github-light",
      dark: "vesper",
    },
  },
});
