import { loader } from "fumadocs-core/source";

import { docs } from "../../.source/server";

/**
 * Documentation content source — single Fumadocs source rooted at
 * `/documentation`.
 *
 * @remarks
 * `baseUrl` decouples the URL space from the content directory: pages
 * live under `src/app/(docs)/documentation/_content/` (colocated with
 * the route) but render at `/documentation/<slug>` because the route
 * segment is `documentation/`. This file is the single point of truth
 * for that mapping — `[...slug]/page.tsx` and `layout.tsx` both consume
 * the exported `source`.
 *
 * The `docs` import comes from `.source/`, regenerated by
 * `fumadocs-mdx` on each `next dev` / `next build` (wired through
 * `next.config.ts`'s `createMDX` plugin). The folder is gitignored.
 *
 * @see source.config.ts — content registry that drives the codegen.
 * @see src/app/(docs)/documentation/[...slug]/page.tsx — the renderer.
 */
export const source = loader({
  baseUrl: "/documentation",
  source: docs.toFumadocsSource(),
});
