import "server-only";

import { createOpenAPI } from "fumadocs-openapi/server";
import { createAPIPage } from "fumadocs-openapi/ui";
import path from "node:path";

/**
 * `input` is the function form so MDX references the document by stable key
 * `"openapi.snapshot.json"` — `path.resolve` happens once server-side, MDX
 * stays portable. Snapshot is regenerated by `tests/contract/openapi.test.ts`
 * so the rendered reference can't drift from the live Zod validators.
 */
export const openapi = createOpenAPI({
  input: () => ({
    "openapi.snapshot.json": path.resolve("./openapi.snapshot.json"),
  }),
});

/** `github-light` + `vesper` — Fumadocs canonical pairing, same theme as prose code blocks. */
export const APIPage = createAPIPage(openapi, {
  shikiOptions: {
    themes: {
      light: "github-light",
      dark: "vesper",
    },
  },
});
