import type { MetadataRoute } from "next";

import { getAppUrl } from "@/server/app-url";

/**
 * `/robots.txt` — auto-generated by Next.js from the default export
 * of this file.
 *
 * @remarks
 * Policy:
 *
 *   - Index everything in the marketing zone (no specific allow/disallow
 *     — the default is "allow all").
 *   - Disallow `/api/*` and `/auth/*` — they're either JSON responses
 *     or redirect pipelines, useless for search engines and potentially
 *     confusing if indexed.
 *   - Disallow `/settings/*`, `/users/*`, `/replays/*` — the authed
 *     dashboard. Anonymous crawlers can't reach those anyway (the
 *     proxy bounces them to `/sign-in`), but telling crawlers to skip
 *     saves crawl budget.
 *   - Point `sitemap` at the generated sitemap route.
 *
 * Base URL comes from the shared `getAppUrl()` helper so switching
 * hosts is one line in `src/server/app-url.ts`.
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = getAppUrl();
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/auth/", "/settings/", "/users/", "/replays/", "/invite/"],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
