import type { MetadataRoute } from "next";

import { DEFAULT_LOCALE, LOCALES } from "@/i18n/config";
import { source } from "@/lib/source";
import { getAppUrl } from "@/server/app-url";

/**
 * `/sitemap.xml` — auto-generated by Next.js from the default export.
 *
 * @remarks
 * Two indexable surfaces:
 *
 *   1. **Marketing landing** at `/` — emitted per locale with
 *      `alternates.languages` covering every other locale (the
 *      canonical hreflang pattern). Default locale renders without a
 *      URL prefix, non-default locales carry theirs (`/uk`, `/de`,
 *      etc.) — matches `localePrefix: "as-needed"` in `routing.ts`.
 *   2. **Documentation pages** under `/documentation/*` — English-only
 *      by deliberate design (the docs zone lives outside the
 *      `[locale]/` pipeline), so no hreflang alternates. Enumerated
 *      from the Fumadocs source — adding a new MDX file or `meta.json`
 *      ordering automatically reflects in the sitemap on next deploy.
 *
 * Every dashboard route is auth-gated and excluded by `robots.ts`, so
 * it doesn't belong here either way.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = getAppUrl();
  const now = new Date();

  // Marketing landing — locale-aware with hreflang alternates.
  const urlFor = (locale: string) => (locale === DEFAULT_LOCALE ? `${baseUrl}/` : `${baseUrl}/${locale}`);
  const languages = Object.fromEntries(LOCALES.map((locale) => [locale, urlFor(locale)]));

  const marketing: MetadataRoute.Sitemap = LOCALES.map((locale) => ({
    url: urlFor(locale),
    lastModified: now,
    changeFrequency: "monthly",
    priority: locale === DEFAULT_LOCALE ? 1.0 : 0.9,
    alternates: { languages },
  }));

  // Documentation — English-only, includes the docs landing (`/documentation`)
  // plus every MDX page resolved from `_content/`.
  const docs: MetadataRoute.Sitemap = [
    {
      url: `${baseUrl}/documentation`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    ...source.getPages().map((page) => ({
      url: `${baseUrl}${page.url}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
  ];

  return [...marketing, ...docs];
}
