import type { MetadataRoute } from "next";

import { DEFAULT_LOCALE, LOCALES } from "@/i18n/config";
import { getAppUrl } from "@/server/app-url";

/**
 * `/sitemap.xml` — auto-generated by Next.js from the default export.
 *
 * @remarks
 * Today the only public-indexable surface is the marketing landing
 * at `/`. Every dashboard route is auth-gated and excluded by
 * `robots.ts`, so it doesn't belong here either way.
 *
 * Each locale gets its own entry with `alternates.languages` pointing
 * at every other locale — that's the canonical hreflang pattern, and
 * it tells Google to serve the right language variant per visitor
 * without treating the pages as duplicates. Default locale renders
 * without a URL prefix (`/`), non-default locales carry theirs
 * (`/uk`, `/de`, etc.), matching the `localePrefix: "as-needed"`
 * strategy declared in `src/i18n/routing.ts`.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = getAppUrl();

  const urlFor = (locale: string) => (locale === DEFAULT_LOCALE ? `${baseUrl}/` : `${baseUrl}/${locale}`);

  const languages = Object.fromEntries(LOCALES.map((locale) => [locale, urlFor(locale)]));

  return LOCALES.map((locale) => ({
    url: urlFor(locale),
    lastModified: new Date(),
    changeFrequency: "monthly",
    priority: locale === DEFAULT_LOCALE ? 1.0 : 0.9,
    alternates: { languages },
  }));
}
